workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - package:
          requires:
            - build
      - deploy:
          requires:
            - package
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
