version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run:
          name: テスト＆ビルド
          command: echo 'テストとビルドをやりました。'
  deploy_develop:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - deploy:
          name: デプロイ
          command: echo 'デプロイをしました。'
  build_register:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: バイナリビルド
          command: echo 'Jarなど「デプロイ出来るもの」を作成しました。'
      - run:
          name: リポジトリデプロイ
          command: echo 'インハウスリポジトリやS3など「バイナリの置き場」に配置しました。'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy_develop:
          requires:
            - build
          filters:
            branches:
              only: master
      - build_register:
          requires:
            - build
          filters:
            rags:
              only: /v.*/
            branches:
              ignore: /.*/
