version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - checkout
      - run:
          name: テスト＆ビルド
          command: echo 'テストとビルドをやりました。'
  deploy_develop:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - deploy:
          name: デプロイ
          command: echo 'デプロイをしました。'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy_develop:
          requires:
            - build
          filters:
            branches:
              only: master
