version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    steps:
      - run:
          name: 開始通知
          command: curl -X POST ${SLACK_WEBHOOK_URL} -H 'content-type: application/json' -d '{"text": "CircleCIでのビルドを開始します。"}'
      - checkout
      - run:
          name: テスト＆ビルド
          command: echo 'テストとビルドをやりました。'
  deploy_develop:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - deploy:
          name: デプロイ
          command: echo 'デプロイをしました。'
  build_register:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: バイナリビルド
          command: |
            mkdir -p ./build/libs
            echo 'バイナリのつもり' > build/libs/tess-sample.jar
      - run:
          name: リポジトリデプロイ
          command: echo 'インハウスリポジトリやS3など「バイナリの置き場」に配置しました。'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy_develop:
          requires:
            - build
          filters:
            branches:
              only: master
      - build_register:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
